### PR TITLE
Update supported system distributions

### PR DESCRIPTION
**Pull request by elcomtik**
## Description

Added:
- RockyLinux 9
- Fedora36

Removed:
- Fedora34

## Related Issue

https://github.com/mrlesmithjr/dockerfiles/issues

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Chore (non-breaking change that does not add functionality or fix an issue)

## Checklist:

- [x] I have read the **CONTRIBUTING** document.
- [x] I have run the pre-merge tests locally and they pass.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

### CODE REVIEW

**Review by mrlesmithjr — APPROVED** [review]

**Comment by elcomtik** [comment]
Looks like using ubuntu-latest as run-on for lint is not stable, because it changed from ubuntu 20.04 to 22.04. The current ubuntu-latest probably doesn't contain brew. I'll test it with the 20.04 specified.

**Review by mrlesmithjr — APPROVED** [review]

**Comment by elcomtik** [comment]
I found that it's not ubuntu-latest issue, but something more serious https://github.com/actions/runner-images/issues/6283. 

I'll try to fix this for all affected workflows.

**Comment by elcomtik** [comment]
It looks like the latest commits fixed the issue, I had to update the pre-commit config because the version of shell-fmt used wasn't available anymore.

It should be OK, now.

**Comment by elcomtik** [comment]
Fedora 35/36 build failed on out of memory error https://github.com/mrlesmithjr/dockerfiles/actions/runs/3191354138/jobs/5207594015#step:6:360.

Could you please try to re-run these two jobs?

**Comment by mrlesmithjr** [comment]
I think these are good now and merged.

**Pull request merged**
